# Generated by Django 4.2.7 on 2023-11-02 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0002_alter_actionproject_options_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('position', models.IntegerField(verbose_name='Позиция')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Чеклист у задачи',
                'verbose_name_plural': 'Чеклисты у задачи',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('code', models.CharField(max_length=128, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Проект')),
                ('section_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.sectionproject', verbose_name='Этап в проекте')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_created', to='user.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='UserPositionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.importancelevel', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Должность пользователя в задачах',
                'verbose_name_plural': 'Должность пользователя в задачах',
            },
        ),
        migrations.CreateModel(
            name='UserPositionTaskToTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.userpositiontask', verbose_name='Должность пользователя в задачах')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь к задаче',
                'verbose_name_plural': 'Пользователи к задаче',
            },
        ),
        migrations.CreateModel(
            name='SubtaskChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('position', models.IntegerField(verbose_name='Позиция')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.checklisttask', verbose_name='Чеклист')),
            ],
            options={
                'verbose_name': 'Чеклист у задачи',
                'verbose_name_plural': 'Чеклисты у задачи',
            },
        ),
        migrations.CreateModel(
            name='CommentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.userpositiontasktotask', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий у задачи',
                'verbose_name_plural': 'Комментарии у задачи',
            },
        ),
        migrations.AddField(
            model_name='checklisttask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.userpositiontasktotask', verbose_name='Пользователь'),
        ),
    ]
