# Generated by Django 4.2.7 on 2023-11-02 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_usertoproject'),
        ('task', '0004_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='section_project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.sectionproject', verbose_name='Этап в проекте'),
        ),
    ]
