# Generated by Django 4.2.7 on 2023-11-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_section_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttask',
            name='completed_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='subtaskchecklist',
            name='completed_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=None, null=True, verbose_name='Крайний срок'),
        ),
    ]
