# Generated by Django 4.2.7 on 2023-11-03 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('task', '0009_alter_subtaskchecklist_options_alter_task_director'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPositionTaskToTask',
            new_name='UserToTask',
        ),
    ]
