# Generated by Django 4.2.7 on 2023-11-02 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Активность в проекте',
                'verbose_name_plural': 'Активности в проекте',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('code', models.CharField(max_length=128, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(upload_to='project/images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='SectionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('position', models.CharField(max_length=128, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Этап в проекте',
                'verbose_name_plural': 'Этапы в проекте',
            },
        ),
        migrations.CreateModel(
            name='RoleProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.importancelevel', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Роль в проекте',
                'verbose_name_plural': 'Роли в проекте',
            },
        ),
        migrations.CreateModel(
            name='HistoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.actionproject', verbose_name='Активность')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_projects_created', to='user.userprofile', verbose_name='Пользователь')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_projects_affected', to='user.userprofile', verbose_name='Жертва')),
            ],
            options={
                'verbose_name': 'История по проекту',
                'verbose_name_plural': 'История по проекту',
            },
        ),
    ]
