# Generated by Django 4.2.7 on 2023-11-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionproject',
            options={'verbose_name': 'Активность проекта', 'verbose_name_plural': 'Активности проектов'},
        ),
        migrations.AlterModelOptions(
            name='historyproject',
            options={'verbose_name': 'История проекта', 'verbose_name_plural': 'История проекта'},
        ),
        migrations.AlterModelOptions(
            name='sectionproject',
            options={'verbose_name': 'Этапы проекта', 'verbose_name_plural': 'Этапы проектов'},
        ),
    ]
