# Generated by Django 4.2.7 on 2023-11-02 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0002_alter_actionproject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Проект')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.roleproject', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь к проекту',
                'verbose_name_plural': 'Пользователь к проектам',
            },
        ),
    ]
