# Generated by Django 4.2.7 on 2023-11-03 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0004_project_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='Админ'),
            preserve_default=False,
        ),
    ]
